name: Jekyll Themes
url: http://Babel.github.io
description: Insert tagline here
remote_theme : williamcanin/typing-jekyll-template

permalink: /themes/:title/

gems: [jekyll-paginate]

highlighter: pygments
paginate: 20

markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
